config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about", as: "about"
  get "search" => "searches#search"

  root to: "homes#top"
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :index, :show, :update, :destroy] do
  resource :relationships, only: [:create, :destroy]
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'followeds' => 'relationships#followeds', as: 'followeds'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back fallback_location: root_path 非同期化のため削除
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back fallback_location: root_path 非同期化のため削除

  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
      <% if book.favorited_by?(current_user) %>
      <p>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        ♥<%= book.favorites.count %>
      <% end %>
      </p>
      <% else %>
      <p>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        ♡<%= book.favorites.count %>
      <% end %>
      </p>
      <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");