config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about", as: "about"
  get "search" => "searches#search"

  root to: "homes#top"
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :index, :show, :update, :destroy] do
  resource :relationships, only: [:create, :destroy]
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'followeds' => 'relationships#followeds', as: 'followeds'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :profile_image
  validates :name,presence: true, uniqueness: true, length: {minimum: 2,maximum: 20}
  validates :introduction, length: {maximum: 50}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :books, dependent: :destroy
has_many :comments, dependent: :destroy
has_many :favorites, dependent: :destroy

has_many :relationship,class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :followeds, through: :relationship, source: :followed

has_many :reverse_relationship,class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_relationship, source: :follower




    def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
    end

    def follow(user_id)
      relationship.create(followed_id: user_id)
    end

    def unfollow(user_id)
      relationship.find_by(followed_id: user_id).destroy
    end

    def followed?(user)
      followeds.include?(user)
    end
    
    def self.looks(search, word)
      if search == "perfect_match"
        @user = User.where("name LIKE?", "#{word}")
      elsif search == "foward_match"
        @user = User.where("name LIKE?", "#{word}%")
      elsif search == "backward_match"
        @user = User.where("name LIKE?", "%#{word}")
      elsif search == "partial_match"
        @user = User.where("name LIKE?", "%#{word}%")
      else
        @user = User.all
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @user = user.new
  end

  def create
    @user = user.new(user_params)
    @user.save
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
  end



  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
  user_id = params[:id].to_i
  login_user_id = current_user.id
   if(user_id != login_user_id)
    redirect_to user_path(current_user.id)
   end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
   <h2 class="mt-3">New book</h2>


   <%= form_with model: Book.new do |f| %>
   <div class="form-group">
    <h5>Title</h5>
     <%= f.text_field :title %>
   </div>
   <div class="form-group">
    <h5>Opinion</h5>
     <%= f.text_area :body %>
   </div>
   <div class="form-group">
     <%= f.submit 'Create Book' %>
   </div>
   <% end %>
  </div>

app/views/users/edit.html.erb
<main>
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>User info</h2>

     <% if @user.errors.any? %>
  　 <%= @user.errors.count %>error prohibited this obj from being saved:
     <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
     </ul>
     <% end %>

      <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
      <div class="form-group">
     　 <label >Name</label>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
    　  <label>Image</label>
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div class="form-group">
    　  <label>Introduction</label>
      　<%= f.text_area :introduction %>
      </div>
      <div class="form-group">
    　  <%= f.submit 'Update User' %>
      </div>
      <% end %>
    </div>
  </div>
 </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
   <%= render partial: "searches/search" %>
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
     <% if @user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, size: "200x200" %>
     <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
     <% end %>

   <table class="table">
    <tbody>
     <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
     </tr>
    </tbody>
   </table>
   <div class="row">
    <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>

 <%= render 'user', user: @user %>

  <div class="col-md-8 offset-md-1">
  <h2>Users</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
    </thead>
    <tbody>
     <tr>
      <% @users.each do |user| %>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.followeds.count %></td>
      <td>フォロワー数: <%= user.followers.count %></td>
      <td>
       <% if current_user.followed?(user) %>
  　     <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
 　     <% else %>
   　    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
  　    <% end %>
  　   </td>
      <td><%= link_to "Show", user_path(user.id) %></td>
   　 </tr>
      <% end %>

     </tbody>
    </table>
   </div>
  </div>
 </div>
</main>

app/views/users/new.html.erb
<h2>User new</h2>

app/views/users/show.html.erb
<main>
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
     <% if @user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, size: "200x200" %>
     <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
     <% end %>

   <table class="table">
    <tbody>
     <tr>
      <th>name</th>
      <th><%= @user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
     </tr>
      <tr>
       <th>follows</th>
       <th><%= link_to @user.followeds.count, user_followeds_path(@user.id) %></th>
     </tr>
      <tr>
       <th>followers</th>
       <th><%= link_to @user.followers.count, user_followers_path(@user.id) %></th>
     </tr>
    </tbody>
   </table>
   <div>
  　 <% if current_user.followed?(@user) %>
  　  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-info" %>
 　  <% else %>
   　 <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success" %>
  　 <% end %>
   </div>
   <div class="row">
    <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>
  <%= render 'user', user: @user %>

  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
      <tbody>
       <tr>
        <% @book.each do |book| %>
        <td><%= link_to user_path(@user.id) do %>
         <%= image_tag book.user.get_profile_image(100,100) %>
         <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
    　 </tr>
       <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>
</main>