config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about", as: "about"
  get "search" => "searches#search"

  root to: "homes#top"
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :index, :show, :update, :destroy] do
  resource :relationships, only: [:create, :destroy]
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'followeds' => 'relationships#followeds', as: 'followeds'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord


    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy


    validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
    # 検索条件の分岐
    def self.looks(search, word)
      if search == "perfect_match"
        @book = Book.where("title LIKE?", "#{word}")
      elsif search == "foward_match"
        @book = Book.where("title LIKE?", "#{word}%")
      elsif search == "backward_match"
        @book = Book.where("title LIKE?", "%#{word}")
      elsif search == "partial_match"
        @book = Book.where("title LIKE?", "%#{word}%")
      else
        @book = Book.all
      end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = Comment.new
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
      render:edit
    end
  end

  def destroy
     @book = Book.find(params[:id])
     @book.destroy
     redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="container px-5 px-sm-0">
       <% if book.errors.any? %>
       <%= book.errors.count %>errors prohibited this obj from being saved:
       <ul>
      <% book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
       </ul>
     <% end %>
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
     <% if user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, size: "200x200" %>
     <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
     <% end %>

   <table class="table">
    <tbody>
     <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
     </tr>
    </tbody>
   </table>
   <div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>

      <h2 class="mt-3">New book</h2>
   <%= form_with model: Book.new do |f| %>
   <div class="form-group">
    <h5>Title</h5>
     <%= f.text_field :title %>
   </div>
   <div class="form-group">
    <h5>Opinion</h5>
     <%= f.text_area :body %>
   </div>
   <div class="form-group">
     <%= f.submit 'Create Book' %>
   </div>
   <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>Editing Book</h2>

      <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
       </ul>
     <% end %>
     <accept-charset="UTF-8"method="post">
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
      <div class="form-group">
      <label>Title</label>
      <%= f.text_field :title %>
      </div>
      <div class="form-group">
      <label>Opinion</label>
      <%= f.text_area :body %>
      </div>
      <div class="form-group">
      <%= f.submit 'Update Book' %>
      </div>
      <% end %>
      <%= link_to "Show",book_path(@book.id) %>
      <%= link_to "Back",books_path %>
      </accept-charset>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
 <div class="container px-5 px-sm-0">
     <%= render partial: "searches/search" %>
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
       </ul>
     <% end %>
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
     <% if @user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, size: "200x200" %>
     <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
     <% end %>

   <table class="table">
    <tbody>
     <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
     </tr>
    </tbody>
   </table>
   <div class="row">
    <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>

      <h2 class="mt-3">New book</h2>
   <%= form_with model: Book.new do |f| %>
   <div class="form-group">
    <h5>Title</h5>
     <%= f.text_field :title %>
   </div>
   <div class="form-group">
    <h5>Opinion</h5>
     <%= f.text_area :body %>
   </div>
   <div class="form-group">
     <%= f.submit 'Create Book' %>
   </div>
   <% end %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
     </tr>
    </thead>
    <tbody>
     <tr>
      <% @books.each do |book| %>
      <td>
       <%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <!--部分テンプレート化-->
      <td id="favorite_buttons_<%= book.id %>">
       <%= render "favorites/favorites", book: book %>
      </td>
      <td>
        <p>コメント数：<%= book.comments.count %></p>
      </td>
   　 </tr>
      <% end %>

     </tbody>
    </table>
   </div>
  </div>
 </div>
</main>

app/views/books/new.html.erb
<h2>Books new</h2>

app/views/books/show.html.erb
<main>
<div class="container px-5 px-sm-0">
       <% if @book.errors.any? %>
       <%= @book.errors.count %>errors prohibited this obj from being saved:
       <ul>
      <% book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
       </ul>
     <% end %>
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
     <% if @user.profile_image.attached? %>
      <%= image_tag current_user.profile_image, size: "200x200" %>
     <% else %>
      <%= image_tag 'no_image', size: "200x200" %>
     <% end %>

   <table class="table">
    <tbody>
     <tr>
      <th>name</th>
      <th><%= @user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
     </tr>
    </tbody>
   </table>
   <div class="row">
    <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>

      <h2 class="mt-3">New book</h2>
   <%= form_with model: Book.new do |f| %>
   <div class="form-group">
    <h5>Title</h5>
     <%= f.text_field :title %>
   </div>
   <div class="form-group">
    <h5>Opinion</h5>
     <%= f.text_area :body %>
   </div>
   <div class="form-group">
     <%= f.submit 'Create Book' %>
   </div>
   <% end %>
  </div>
 <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
   <tbody>
    <tr>
      <td><%= link_to user_path(@user.id) do %>
       <%= image_tag @book.user.get_profile_image(100,100) %><br>
       <% end %>
　　　 <%= link_to @book.user.name, user_path(@user.id) %>
      </td>
      <td><%= link_to @book.title, book_path(@book.id) %></td>
      <td><%= @book.body %></td>

      <!--いいね機能部分テンプレート化-->
      <td id="favorite_buttons_<%= @book.id %>">
       <%= render "favorites/favorites", book: @book %>
      </td>
      <td>
        <p>コメント数：<%= @book.comments.count %></p>
      </td>
      <td>
       <% if @book.user == current_user %>
       <%= link_to "Edit", edit_book_path(@book.id) %>
       <% end %>
      </td>

      <td>
       <% if @book.user == current_user %>
       <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
       <% end %>
      </td>
    </tbody>
  </table>
      <!--投稿一覧部分テンプレート化-->
      <div class="area_comments">
        <%= render 'comments/post_comments', book: @book %>
      </div>
      <!--投稿フォーム部分テンプレート化-->
      <div class="new_comments">
        <%= render 'comments/form_comments', book: @book, comment: @comment %>
      </div>
 </div>

  </div>
 </div>
</main>