config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => "homes#about", as: "about"
  get "search" => "searches#search"

  root to: "homes#top"
  devise_for :users

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
   resources :comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:new, :edit, :index, :show, :update, :destroy] do
  resource :relationships, only: [:create, :destroy]
   get 'followers' => 'relationships#followers', as: 'followers'
   get 'followeds' => 'relationships#followeds', as: 'followeds'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # ユーザーがログインしているか確認
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
 <div class="search_form">
   <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <!--検索するモデルを探す-->
    <%= f.select :range, options_for_select([['User'], ['Book']]) %>
    <!--検索条件を記述-->
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-arimary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<%= render partial: "searches/search" %>
<h2>Results index</h2>

<table class="table table-hover table-inverse">


  <% if @range == "User" %>
    <tbody>
      <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
     </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(50,50) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followeds.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
      <tbody>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </tr>

       <% @books.each do |book| %>
        <tr>
          <td>
           <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(50,50) %>
           <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>